server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:39.108.136.61}:${REGISTER_PORT:8848}
      config:
        server-addr: ${REGISTER_HOST:39.108.136.61}:${REGISTER_PORT:8848}
        file-extension: yml
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:39.108.136.61}:${SENTINEL_DASHBOARD_PORT:8021}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:39.108.136.61}
    port: ${RABBIT_MQ_PORT:1884}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admins}
    redis:
      host: ${REDIS_HOST:39.108.136.61}
      port: ${REDIS_PORT:6386}
      password: ${REDIS_PASSWORD:w+.8?2267}
      lettuce:
        pool:
          max-active: 300

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:39.108.136.61}:${DATASOURCE_PORT:8386}/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:%dt6$#@%s}